### ISSUE TITLE
✨feat : Route & lazy & navigate & etc...

### ISSUE THREAD

**Issue by nada1221** [codestates-seb/seb40_main_001#126]
## Description

✨feat : Route & lazy & navigate & etc...

## Todo

- [x] Route 설정하기
- [x] Lazy Loading 설정하기
- [x] Arounder detail page API 연동
- [ ] '' 댓글 관련 데이터 통신 보고 수정하기
- [x] Landing Page 전역상태관리 로그인 유무 확인해야함.

## ETC
- 주의 사항 혹은 기타 내용
- 본격적인 백엔드와의 협업이 시작되는 시기이므로, 최대한 소통하고 조율해야함
