### ISSUE TITLE
 🩹 Chore: 글쓰기 페이지 수정사항

### ISSUE THREAD

**Issue by haileyport** [codestates-seb/seb40_main_001#184]
## Description

글쓰기 페이지 내에서 수정되어야 할 사항입니다.

## Todo

- [x] 뒤로가기 활성화
- [x] Create가 아닌 Edit인 경우 기존 데이터 유지
- [x] Edit인 경우 api endpoint 변경

## ETC
- Edit은 상세 페이지 작업 종료 후 진행합니다.

**Comment by haileyport** [comment]
- [] 캐러셀에서 ALL 제거

**Comment by haileyport** [comment]
- [ ] 이미지 없는 경우 이미지 api 실행 안 되게 수정하기

**Comment by haileyport** [comment]
- [ ] 이미지 수정 로직 추가
