### ISSUE TITLE
✨ Feat: 전체 주소 GET API

### ISSUE THREAD

**Issue by Qone2** [codestates-seb/seb40_main_001#28]
## Description

전체 주소 리스트를 조회합니다.

## Todo

- [x] Controller Layer: GET handler Method 구현
- [x] Service Layer: findAll Method 구현
- [x] Data Access Layer: 관련로직 구현

## ETC
- 객체지향적 설계
