### ISSUE TITLE
✨ Feat: 운친모집 함께하기 신청 POST API

### ISSUE THREAD

**Issue by Qone2** [codestates-seb/seb40_main_001#29]
## Description

이미 있는 운친모집에 함께하기를 신청합니다.

## Todo

- [ ] Controller Layer : POST Handler Method 구현
- [ ] Service Layer : Create Method 구현
- [ ] Data Access layer : 관련 로직 구현

## ETC
- 객체지향적 설계 고려하기
