### ISSUE TITLE
#Feat : Excercise 모집 글 PATCH API

### ISSUE THREAD

**Issue by hyeongiii** [codestates-seb/seb40_main_001#3]
## Description

운동 친구 모집글을 작성하는 PATCH API를 구현합니다.
## Todo

- [ ] Controller layer : patch handler Method 구현
- [ ] Service layer : update Method 및 로직 구현
- [ ] Repository layer : 관련 로직 구현

## ETC
- 객체지향적 설계 고려하기
