### ISSUE TITLE
✅ Test: Exercise 테스트

### ISSUE THREAD

**Issue by hyeongiii** [codestates-seb/seb40_main_001#317]
## Description

Exercise 도메인의 테스트 코드를 작성합니다.

## Todo

- [ ] Controller layer 단위 테스트
- [ ] Service layer 단위 테스트
- [ ] Exercise 통합 테스트

## ETC
- Data Access layer 단위 테스트 (후순위)
