### ISSUE TITLE
✅ Test: 댓글 테스트

### ISSUE THREAD

**Issue by yujung-Jang** [codestates-seb/seb40_main_001#326]
## Description

댓글 도메인의 테스트 코드를 작성합니다.

## Todo

- [ ] Controller Layer 단위 테스트
- [ ] Service Layer 단위 테스트
- [ ] Comment 통합 테스트

## ETC
- Data Access Layer 단위 테스트 (후순위)
