### ISSUE TITLE
✨ Feat: 마이페이지 조회 GET API

### ISSUE THREAD

**Issue by yujung-Jang** [codestates-seb/seb40_main_001#7]
## Description

마이페이지를 조회하는 GET API를 구현합니다.

## Todo

- [x] Controller Layer : GET Handler Method 구현
- [x] Service Layer : Get Method 구현
- [x] Data Access Layer : 관련 로직 구현

## ETC
- 객체지향 설계하기
