### ISSUE TITLE
✨ Feat: 운동 모집 글 DELETE API

### ISSUE THREAD

**Issue by hyeongiii** [codestates-seb/seb40_main_001#8]
## Description

운동 친구 모집글을 삭제하는 DELETE API를 구현합니다.

## Todo

- [ ] Controller layer : delete handler Method 구현
- [ ] Service layer : delete Method 및 로직 구현
- [ ] Data Access layer : 관련 로직 구현

## ETC
- 객체지향적 설계 고려하기
